//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiometricFingerprintApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class cours
    {
        public int id { get; set; }
        public int department { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public int year { get; set; }
        public int semester { get; set; }
    }
}
