//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiometricFingerprintApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projdbEntities : DbContext
    {
        public projdbEntities()
            : base("name=projdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<resit> resits { get; set; }
        public virtual DbSet<studcourse> studcourses { get; set; }
    }
}
