//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiometricFingerprintApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string matricno { get; set; }
        public int stlevel { get; set; }
        public int dept { get; set; }
        public int state { get; set; }
        public byte[] passport { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public Nullable<int> modified_by { get; set; }
    }
}
